version: "3.9"

services:
  db:
    image: postgres:16-alpine
    container_name: strapi-db-prod
    restart: unless-stopped
    env_file:
      - .env
    environment:
      POSTGRES_DB: ${DATABASE_NAME}
      POSTGRES_USER: ${DATABASE_USERNAME}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - /mnt/volume_nyc1_01/postgres:/var/lib/postgresql/data

  strapi:
    build:
      context: .
      dockerfile: Dockerfile.prod
    container_name: lima-strapi-prod-app
    restart: unless-stopped
    env_file:
      - .env
    environment:
      NODE_ENV: production
      DATABASE_CLIENT: postgres
      DATABASE_HOST: db
      DATABASE_PORT: 5432
      DATABASE_NAME: ${DATABASE_NAME}
      DATABASE_USERNAME: ${DATABASE_USERNAME}
      DATABASE_PASSWORD: ${DATABASE_PASSWORD}
    ports:
      - "1337:1337"
    depends_on:
      - db
    volumes:
      - /mnt/volume_nyc1_01/uploads:/app/public/uploads